### ISSUE TITLE
Why use the edge of the ligand as the center of receptor voxelization? In short why -12?

### ISSUE THREAD

**Issue by AberChiong** [abdulsalam-bande/KDeep#1]
https://github.com/abdulsalam-bande/KDeep/blob/f6bb4e10973ff590acdb55687f8c84b3782aa538/training_with_htmd/feature-extraction-htmd.py#L50

Hi author, I'm refactoring your code for my master's project. I noticed that you kept the voxel center of the receptor protein at the edge of the ligand small molecule during voxelization. Can you explain to me the purpose of this step? As far as I know, doing so may result in the loss of the identity of part of the residues (the ligand is located at the edge of the receptor protein). I think it is actually better to simply use the center of the ligand small molecule as the center of protein voxelization. Looking forward to your reply :)

**Comment by abdulsalam-bande** [comment]
Hello,

Firstly, I'd like to clarify that I am not the original author of this work. I forked the project and made edits to it.

Regarding your query, I agree with you about the potential loss of the identity of part of the residues when keeping the voxel center of the receptor protein at the edge of the ligand small molecule during voxelization. 

I would recommend trying out your idea and comparing the results with the existing method. It might offer improved or more accurate results.

Best wishes with your master's project.

**Comment by AberChiong** [comment]
Thanks for your reply! 

I'm going to try something like you said. 👍
